name: stacktimers
description: Stack timer
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.0.3
  flutter_slidable: ^1.3.0
  get: ^4.6.5
  intl: ^0.17.0
  sqflite: ^2.0.2+1
  sqflite_common_ffi: ^2.1.1
  flutter_ringtone_player: ^3.2.0
  flutter_picker: ^2.0.3
  golden_toolkit: ^0.13.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: IPAGothic
      fonts:
        - asset: fonts/ipag.ttf
    - family: IPAPGothic
      fonts:
        - asset: fonts/ipagp.ttf
    - family: IPAMincho
      fonts:
        - asset: fonts/ipam.ttf
    - family: IPAPMincho
      fonts:
        - asset: fonts/ipamp.ttf
